applibrary/config/routes.rb
Rails.application.routes.draw do
  resources:books
 #Session routes

 get 'visitors/index'
 root 'visitors#index'

 get 'visitors/search', to: 'visitors#search'

##################################################################
 get 'login', to: 'session#new'
 post 'login', to: 'session#create'
 delete 'logout', to: 'session#destroy'
 get 'logout', to: 'session#destroy'


#Controller user - book router##########################################
 get 'users/index'
 get'/users/books', to: 'users#books'
 get '/users/books/:id', to: 'users#show_book', as: 'show_users_books'
 get'/users/loans', to: 'users#loans'
 





#LIBRARIANS#################################################################
 #librarians Users routes############################################################
 get 'librarians/index'
 get'/librarians/users', to: 'librarians#users'
 match '/librarians/users/signup', to:'librarians#new_user', via: 'get'
 post '/librarians/users', to: 'librarians#create_user'
 get '/librarians/users/:id', to: 'librarians#show_user', as: 'show_librarians_users'
 get '/librarians/:id/edit_user', to: 'librarians#edit_user',as: 'edit_librarians_users'
 put '/librarians/users/:id', to: 'librarians#update_user'
 delete'/librarians/users/:id', to: 'librarians#delete_user', as: 'delete_librarians_users'


 #librarian loan route#############################################################
  get'/librarians/loans', to: 'librarians#loans'
  get'/librarians/loans/new_loan', to:'librarians#new_loan'
  post '/librarians/loans', to: 'librarians#create_loan'
  get '/librarians/:id/edit_loan', to: 'librarians#edit_loan',as: 'edit_librarians_loans'
  put '/librarians/loans/:id', to: 'librarians#update_loan'
  delete'/librarians/loans/:id', to: 'librarians#delete_loan', as: 'delete_librarians_loans'


#librarian routes books###########################################################
  get'/librarians/books', to: 'librarians#books'
  get '/librarians/books/new_book', to: 'librarians#new_book'
  post '/librarians/books', to: 'librarians#create_book'
  get '/librarians/books/:id', to: 'librarians#show_book', as: 'show_librarians_books'
  get '/librarians/:id/edit_book', to: 'librarians#edit_book',as: 'edit_librarians_books'
  put '/librarians/books/:id', to: 'librarians#update_book'
  delete'/librarians/books/:id', to: 'librarians#delete_book', as: 'delete_librarians_books'

end

applibrary/app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController


  def index

  end

  def search
    keyword = params[:keyword]
    @books = Book.search(keyword)
    #render plain: "#{@books}"
  end

end

applibrary/app/helpers/visitors_helper.rb
module VisitorsHelper
end

applibrary/app/views/visitors/index.html.erb
<main class="container" role="main">
  <div class="jumbotron">
  <br>

<%= link_to 'Iniciar Sesión', login_path ,class:"btn btn-info" %>
<br> <br> <h5>¡Bienvenidos a la Biblio del 210 !<h5><br><br>
<%= form_tag visitors_search_url ,method: :get do =%>
  <%= text_field_tag :keyword, nil, placeholder: "Buscador de libros" %>
  <%= content_tag :button,class:"btn btn-info", type: :submit do %>
    Buscar

  <% end %>

<% end %>
</div>

applibrary/app/views/visitors/search.html.erb
<div class="container">
<br>
<br>

<%= link_to 'Home', visitors_index_path , class:"btn btn-info" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Tilulo</th>
      <th>Autor</th>
      <th>Editorial</th>
      <th>Publicado</th>
      <th>ISBN</th>
      <th>Estado</th>

    </tr>
  </thead>


    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author%></td>
        <td><%= book.editorial%></td>
        <td><%= book.year %></td>
        <td><%= book.isbn %></td>
        <td><%= book.state %></td>
      </tr>

    <% end %>

    <% if @books.size == 0 %>
    "NO EXISTE LIBRO"
    <% end %>
</table>
</div>