applibrary/config/routes.rb
Rails.application.routes.draw do
  resources:books
 #Session routes

 get 'visitors/index'
 root 'visitors#index'

 get 'visitors/search', to: 'visitors#search'

##################################################################
 get 'login', to: 'session#new'
 post 'login', to: 'session#create'
 delete 'logout', to: 'session#destroy'
 get 'logout', to: 'session#destroy'


#Controller user - book router##########################################
 get 'users/index'
 get'/users/books', to: 'users#books'
 get '/users/books/:id', to: 'users#show_book', as: 'show_users_books'
 get'/users/loans', to: 'users#loans'
 





#LIBRARIANS#################################################################
 #librarians Users routes############################################################
 get 'librarians/index'
 get'/librarians/users', to: 'librarians#users'
 match '/librarians/users/signup', to:'librarians#new_user', via: 'get'
 post '/librarians/users', to: 'librarians#create_user'
 get '/librarians/users/:id', to: 'librarians#show_user', as: 'show_librarians_users'
 get '/librarians/:id/edit_user', to: 'librarians#edit_user',as: 'edit_librarians_users'
 put '/librarians/users/:id', to: 'librarians#update_user'
 delete'/librarians/users/:id', to: 'librarians#delete_user', as: 'delete_librarians_users'


 #librarian loan route#############################################################
  get'/librarians/loans', to: 'librarians#loans'
  get'/librarians/loans/new_loan', to:'librarians#new_loan'
  post '/librarians/loans', to: 'librarians#create_loan'
  get '/librarians/:id/edit_loan', to: 'librarians#edit_loan',as: 'edit_librarians_loans'
  put '/librarians/loans/:id', to: 'librarians#update_loan'
  delete'/librarians/loans/:id', to: 'librarians#delete_loan', as: 'delete_librarians_loans'


#librarian routes books###########################################################
  get'/librarians/books', to: 'librarians#books'
  get '/librarians/books/new_book', to: 'librarians#new_book'
  post '/librarians/books', to: 'librarians#create_book'
  get '/librarians/books/:id', to: 'librarians#show_book', as: 'show_librarians_books'
  get '/librarians/:id/edit_book', to: 'librarians#edit_book',as: 'edit_librarians_books'
  put '/librarians/books/:id', to: 'librarians#update_book'
  delete'/librarians/books/:id', to: 'librarians#delete_book', as: 'delete_librarians_books'

end

applibrary/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :loans
  has_many :books, through: :loans

  validates :email, uniqueness: true
  validates :name, :lastname , :phone , :dni , presence: true
  validates :dni, :phone , numericality: true
  validates :name,:lastname  ,length: { minimum: 3 }
  validates :dni, length: { is: 8 }
  validates :password, length: { in: 6..10 }

  validates :role, inclusion: { in: %w(librarian user ) }

  def librarian?
    self.role == 'librarian'
  end


  def self.search(palabra)
      User .where("dni LIKE ? " ,palabra)
  end



#filtar prestamo personal en user
#ver Libros por nombre, editorial, Autor y que se vea el estado

#filtrar para preceptor usuario en prestamo para verificar que no tenga prestamo
#filtar libros por nombre, editorial autosr, etc

end

applibrary/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :require_user

 def index
   @current_user = User.find(session[:user_id])
 end


#metodos de books#######################################################
def books
  @books = Book.all

  if params[:keyword]
    @books = Book.search(params[:keyword])
  else

    @books = Book.all.order('created_at DESC')

  end
end


  def show_book
    @book = Book.find(params[:id])
  end



  #metodos del loan###########################################################

    def loans
        @current_user = User.find(session[:user_id])
        @loans = Loan.all
    end


end

applibrary/app/helpers/users_helper.rb
module UsersHelper
end

applibrary/app/views/users/books.html.erb
<div class="container">
<br>
<h3>Libros</h3>
<br>
<%= link_to 'Home', users_index_path , class:"btn btn-info"%><br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Tilulo</th>
      <th>Autor</th>
      <th>Editorial</th>
      <th>Publicado</th>
      <th>ISBN</th>
      <th>Estado</th>

    </tr>


  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author%></td>
        <td><%= book.editorial%></td>
        <td><%= book.year %></td>
        <td><%= book.isbn %></td>
        <td><%= book.state %></td>
       <td><%= link_to 'Mostrar', show_users_books_path(book.id),  class:"btn btn-info" %></td>

    <% end %>

     <% if @books.size == 0 %>
     "NO EXISTE El LIBRO"
     <% end %>

</table>
</div>

applibrary/app/views/users/index.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-secondary">
   <a class="navbar-brand">La Biblio del 210</a>


   <div class="collapse navbar-collapse" id="navbarsExampleDefault">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item ">
         <a class="nav-link"></a>
       </li>
       <li class="nav-item ">
         <a class="nav-link"<%= link_to 'Libros', users_books_path %> </a>
       </li>
       <li class="nav-item">
         <a class="nav-link" ></a>
       </li>
       <li class="nav-item ">
         <a class="nav-link" <%= link_to 'Mis préstamos',users_loans_path %></a>
       </li>
       <li class="nav-item ">
         <a class="nav-link"></a>
       </li>
       <li class="nav-item ">
         <a class="nav-link" ></a>
       </li>
       <li class="nav-item " align ="right">
         <a class="nav-link" <%= link_to 'Cerrar Sesión', logout_path %></a>
       </li>
        </ul>
 </div>
 </nav>

 <main class="container" role="main">
   <div class="jumbotron">
     <% if @current_user %>
     <p>Hola <%= @current_user.name %></p>

     <% end %>

<%= form_tag users_books_url ,method: :get do  =%>
  <%= text_field_tag :keyword, nil, placeholder: "Buscar libros por título o autor" %>
  <%= content_tag :button, class:"btn btn-info",type: :submit do %>
    Buscar

  <% end %>
  <% end %>
  </div >

applibrary/app/views/users/loans.html.erb
<div class="container">
<br>
<h3>Préstamos</h3>
<br>
<%= link_to 'Home', users_index_path , class:"btn btn-info" %>
<br><br>
<table class="table table-striped">
  <thead>

  <thead>
    <tr>
      <th>Usuario</th>
      <th>Libro</th>
      <th>Inicio</th>
      <th>Fin</th>
      <th>Estado</th>

    </tr>
  </thead>


    <% current_user.loans.each do |loan| %>
      <tr>
        <td><%= loan.user.name %>&nbsp;<%= loan.user.lastname %></td>
        <td><%= loan.book.title%></td>
        <td><%= loan.start_Date %></td>
        <td><%= loan.return_Date %></td>
        <td><%= loan.state %></td>
      </tr>
    <% end %>
    <% if current_user.loans.size == 0 %>
    "NO EXISTE PRÉSTAMO"
    <% end %>
</table>
</div>

applibrary/app/views/users/search.html.erb
<div class="container">
  <br> <br>
  <h3>Libros</h3>
<br>

<%= link_to 'Home', users_index_path, class:"btn btn-info" %>
<table>
  <thead>
    <tr>
      <th>Tilulo</th>
      <th>Autor</th>
      <th>Editorial</th>
      <th>Publicado</th>
      <th>ISBN</th>
      <th>Estado</th>

    </tr>
  </thead>


    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author%></td>
        <td><%= book.editorial%></td>
        <td><%= book.year %></td>
        <td><%= book.isbn %></td>
        <td><%= book.state %></td>


       <td><%= link_to 'Mostrar', show_users_books_path(book.id) %></td>


      </tr>

      <%= link_to 'Volver', users_index_path %>
    <% end %>
    <br> <br>
    <% if @books.size == 0 %>
    "NO EXISTE LIBRO"
    <% end %>




</table>
</div>

applibrary/app/views/users/show_book.html.erb
<div class="container">
<br>

<h3>Libro </h3>
<br>
<div class="form-group">
  <strong>Título:</strong>
  <%= @book.title %>
</div>
<div class="form-group">
  <strong>Autor:</strong>
  <%= @book.author %>
</div>
<div class="form-group">
  <strong>Editorial</strong>
  <%= @book.editorial %>
</div>
<div class="form-group">
  <strong> Año de publicación:</strong>
  <%= @book.year %>
</div>
<div class="form-group">
  <strong>ISBN</strong>
  <%= @book.isbn %>
</div>
<div class="form-group">
  <strong>Estado</strong>
  <%= @book.state %>
</p>

<%= link_to 'Volver', users_index_path, class:"btn btn-info" %>