applibrary/config/routes.rb
Rails.application.routes.draw do
  resources:books
 #Session routes

 get 'visitors/index'
 root 'visitors#index'

 get 'visitors/search', to: 'visitors#search'

##################################################################
 get 'login', to: 'session#new'
 post 'login', to: 'session#create'
 delete 'logout', to: 'session#destroy'
 get 'logout', to: 'session#destroy'


#Controller user - book router##########################################
 get 'users/index'
 get'/users/books', to: 'users#books'
 get '/users/books/:id', to: 'users#show_book', as: 'show_users_books'
 get'/users/loans', to: 'users#loans'
 





#LIBRARIANS#################################################################
 #librarians Users routes############################################################
 get 'librarians/index'
 get'/librarians/users', to: 'librarians#users'
 match '/librarians/users/signup', to:'librarians#new_user', via: 'get'
 post '/librarians/users', to: 'librarians#create_user'
 get '/librarians/users/:id', to: 'librarians#show_user', as: 'show_librarians_users'
 get '/librarians/:id/edit_user', to: 'librarians#edit_user',as: 'edit_librarians_users'
 put '/librarians/users/:id', to: 'librarians#update_user'
 delete'/librarians/users/:id', to: 'librarians#delete_user', as: 'delete_librarians_users'


 #librarian loan route#############################################################
  get'/librarians/loans', to: 'librarians#loans'
  get'/librarians/loans/new_loan', to:'librarians#new_loan'
  post '/librarians/loans', to: 'librarians#create_loan'
  get '/librarians/:id/edit_loan', to: 'librarians#edit_loan',as: 'edit_librarians_loans'
  put '/librarians/loans/:id', to: 'librarians#update_loan'
  delete'/librarians/loans/:id', to: 'librarians#delete_loan', as: 'delete_librarians_loans'


#librarian routes books###########################################################
  get'/librarians/books', to: 'librarians#books'
  get '/librarians/books/new_book', to: 'librarians#new_book'
  post '/librarians/books', to: 'librarians#create_book'
  get '/librarians/books/:id', to: 'librarians#show_book', as: 'show_librarians_books'
  get '/librarians/:id/edit_book', to: 'librarians#edit_book',as: 'edit_librarians_books'
  put '/librarians/books/:id', to: 'librarians#update_book'
  delete'/librarians/books/:id', to: 'librarians#delete_book', as: 'delete_librarians_books'

end

applibrary/app/controllers/librarians_controller.rb
class LibrariansController < ApplicationController

  before_action :require_librarian


  #METODOS DEL LOAN #############################################################################··············································

  def loans
    @loans = Loan.all
    @loans = @loans.map { |loan| loan.expired? }
    if params[:keyword]
      @loans = Loan.search(params[:keyword])
    else
      @loans = Loan.all.order('created_at DESC')
    end
  end


  def new_loan
    @loan = Loan.new

  end


  def create_loan

    @book = Book.find_by_id(params[:loan][:book_id])
    if @book.available?
      #puts loan_params

      @loan = Loan.new(loan_params)
      @loan.save
      flash[:success]="Préstamo creado con éxito"
        redirect_to librarians_loans_path
    else
      flash[:success]="Libro no disponible"
        render :new_loan
    end
  end


  def delete_loan
    @loan = Loan.find(params[:id])
    @loan.destroy
    redirect_to librarians_loans_path
  end

  def edit_loan
    @loan = Loan.find(params[:id])
  end

  def update_loan
    @loan = Loan.find(params[:id])
    if @loan.update(loan_params)
      redirect_to librarians_loans_path
    else
      render :edit_loan
    end
  end



# acciones del book######################################################
  def books
    @books = Book.all
    #@books = @books.map { |book| book.anavailable? }

    if params[:keyword]
      @books = Book.search(params[:keyword])
    else

      @books = Book.all.order('created_at DESC')

    end
  end

  def new_book
    @book = Book.new
  end


  def create_book
    @book = Book.new(book_params)
     if @book.save
       flash[:success]="Libro creado con éxito"
       redirect_to librarians_books_path

     else
       render :new_book

     end
  end


  def show_book
    @book = Book.find(params[:id])
  end


  def delete_book
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to librarians_books_path
  end

  def edit_book
    @book = Book.find(params[:id])
  end

  def update_book
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to librarians_books_path
    else
      render :edit_book
    end
  end


#acciones del usurario#######################################################
  def users
    @users = User.all

    if params[:keyword]
      @users = User.search(params[:keyword])
    else
      @users = User.all.order('created_at DESC')
    end
  end



  def new_user
    @user = User.new
  end


  def create_user
      @user = User.new(user_params)
      @user.role = "user"
      if @user.save
        flash[:success]="Usuario registrado con éxito"
        redirect_to librarians_users_path
      else
      render :new_user
      end
  end


  def show_user
    @user = User.find(params[:id])
  end


  def delete_user
    @user = User.find(params[:id])
    @user.destroy
    redirect_to librarians_users_path
  end


  def edit_user
    @user = User.find(params[:id])
  end


  def update_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to librarians_users_path
    else
      render :edit_user
    end
  end



####PARAMS PERMIT##############################################################

private
    def user_params
      params.require(:user).permit( :id, :name , :lastname , :dni , :email , :phone , :password, :password_confirmation)
    end


    def book_params
      params.require(:book).permit(:title ,:author ,:editorial ,:year , :state ,:isbn)
    end


    def loan_params

      params.require(:loan).permit(:user_id,:book_id , :start_Date , :return_Date , :state )
    end

end

applibrary/app/helpers/librarians_helper.rb
module LibrariansHelper
end

applibrary/app/views/librarians/books.html.erb
<div class="container">
<br>
<h3>Libros</h3>

<br>

 <%= form_tag librarians_books_url ,method: :get do =%>
   <%= text_field_tag :keyword, nil, placeholder: "Buscar por título o autor " %>
   <%= content_tag :button,class:"btn btn-info",type: :submit do  %>
     Buscar

 <% end %>
 <% end %>

<br><br>

 <%= link_to 'Home', librarians_index_path, class:"btn btn-info" %>
<%=link_to 'Crear libro', librarians_books_new_book_path ,class:"btn btn-info" %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Código libro</th>
      <th>Título</th>
      <th>Autor</th>
      <th>Editorial</th>
      <th>Publicado</th>
      <th>ISBN</th>
      <th>Estado</th>

    </tr>
  </thead>

    <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= book.title %></td>
        <td><%= book.author%></td>
        <td><%= book.editorial%></td>
        <td><%= book.year %></td>
        <td><%= book.isbn %></td>
        <td><%= book.state %></td>


        <td><%= link_to 'Mostrar', show_librarians_books_path(book.id), class:"btn btn-info" %></td>
        <td><%= link_to "Editar",edit_librarians_books_path(book.id), class:"btn btn-info" %></td>
        <td><%= link_to "Borrar ",delete_librarians_books_path( book.id),class:"btn btn-warning" , method: :delete, data: { confirm: '¿Deseas eliminar libro?' } %></td>
      </tr>

    <% end %>
    <br> <br>
    <% if @books.size == 0 %>
    "NO EXISTE LIBRO"
    <% end %>




</table>
</div>

applibrary/app/views/librarians/edit_book.html.erb
<div class="container">
  <br>
<h3>Editar Libro</h3>
  <br>
  <%= link_to 'Home', librarians_index_path , class:"btn btn-info"%>
  <br><br>
<%= form_for :book, :url => { :action => :update_book, :id => @book.id },
:method => :put do |f|  %>
<% if @book.errors.any? %>
 <div id="errorExplanation">
   <h2><%= pluralize(@book.errors.count, "error") %> El libro no se puede guardar</h2>
   <ul>
   <% @book.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
 <% end %>

    <div class="form-group">
      <%= f.label :Título %>
      <%= f.text_field :title, class:"form-group" %>
    </div>
    <div class="form-group">
      <%= f.label :Autor %>
      <%= f.text_field :author , class:"form-group"  %>
    </div>
    <div class="form-group">
      <%= f.label :Editorial %>
      <%= f.text_field :editorial, class:"form-group" %>
    </div>
    <div class="form-group">
      <%= f.label :Publicación  %>
      <%= f.date_field :year , class:"form-group"%>
    <div class="form-group">
    <div>Disponible<%= f.radio_button :state, "available" %>  </div>
    <div>No disponible<%= f.radio_button :state, "anavailable" %>  </div>
    </div>

    <div class="form-group">
      <%= f.label :ISBN %>
      <%= f.text_field :isbn , class:"form-group"%>
    </div>

    <div>

      <%= f.submit 'Guardar', class:"btn btn-info" %>

    </div>


<% end %>
</div>

applibrary/app/views/librarians/edit_loan.html.erb
<div class="container">
  <br>
<h3>Editar Préstamo</h3>
  <br>
<%= link_to 'Home', librarians_loans_path , class:"btn btn-info" %>
<br><br>
<%= form_for :loan, :url => { :action => :update_loan, :id => @loan.id },
:method => :put do |loan|  %>
<% if @loan.errors.any? %>
 <div id="errorExplanation">
   <h2><%= pluralize(@loan.errors.count, "error") %> El libro no se puede guardar</h2>
   <ul>
   <% @loan.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
 <% end %>

 <div class="form-group">
   <%= loan.label :Código_Libro %>
   <%= loan.text_field :book_id %>
 </div>

 <div class="form-group">

 <%= loan.label :Número_Socio %>
 <%= loan.text_field :user_id %>
 </div>

<div class="form-group">
 <%= loan.label :Inicio %>
 <%= loan.date_field :start_Date  %>
</div>
<div class="form-group">
 <%= loan.label :Fin  %>
 <%= loan.date_field :return_Date  %>
</div>


  <div class="form-group">
  <div>Activo <%= loan.radio_button :state, "actived" %>  </div>
  <div>Finalizado <%= loan.radio_button :state, "finished" %>  </div>
  <div>Vencido <%= loan.radio_button :state, "expired" %>  </div>
  </div>
    <%= loan.submit 'Guardar',class:"btn btn-info" %>

<% end %>
  </div>

applibrary/app/views/librarians/edit_user.html.erb
<div class="container">
<br>

<h3>Editar</h3>
<br>

<%= link_to 'Home', librarians_users_path , class:"btn btn-info" %><br>
<br>
<%= form_for :user, :url => { :action => :update_user, :id => @user.id },
:method => :put do |user|  %>
<% if @user.errors.any? %>
 <div id="errorExplanation">
   <h2><%= pluralize(@user.errors.count, "error") %> El usuario no se puede editar</h2>
   <ul>
   <% @user.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
 <% end %>

      <div class="form-group">
      <%= user.label :Nombre %>
      <%= user.text_field :name %>
    </div>
      <div class="form-group">
      <%= user.label :Apellido %>
      <%= user.text_field :lastname %>
    </div>
      <div class="form-group">
      <%= user.label :DNI %>
      <%= user.number_field :dni %>
    </div>
      <div class="form-group">
      <%= user.label :Email %>
      <%= user.email_field :email %>
    </div>

      <div class="form-group">
      <%= user.label :Teléfono %>
      <%= user.text_field :phone %>
    </div>
    <div class="form-group">
      <%= user.label :Contraseña %>
      <%= user.text_field :password %>
    </div>
      <div class="form-group">
      <%= user.label :Confirmación %>
      <%= user.text_field :password_confirmation %>
    </div>
      <div class="form-group">
      <%= user.label :Rol %>
      <%= user.text_field :role %>
    </div>

    <div>

      <%= user.submit 'Editar', class:"btn btn-info"   %>

    </div>

<% end %>
</div>

applibrary/app/views/librarians/index.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-secondary">
   <a class="navbar-brand">La Biblio del 210</a>


   <div class="collapse navbar-collapse" id="navbarsExampleDefault">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item ">
         <a class="nav-link"<%= link_to 'Libros', librarians_books_path %></a>
       </li>
       <li class="nav-item ">
         <a class="nav-link" <%= link_to 'Usuarios', librarians_users_path %></a>
       </li>
       <li class="nav-item">
         <a class="nav-link" <%= link_to 'Préstamos', librarians_loans_path %></a>
       </li>
       <li class="nav-item ">
         <a class="nav-link" <%= link_to 'Registrar Usuarios', librarians_users_signup_path %></a>
       </li>
       <li class="nav-item ">
         <a class="nav-link"<%= link_to 'Crear Libros', librarians_books_new_book_path %></a>
       </li>
       <li class="nav-item ">
         <a class="nav-link" <%= link_to 'Crear Préstamos', librarians_loans_new_loan_path %></a>
       </li>
       <li class="nav-item ">
         <a class="nav-link" <%= link_to 'Cerrar Sesión', logout_path %></a>
       </li>
        </ul>
 </div>
 </nav>
    <div class="container">
     <main class="container" role="main">
     <div class="jumbotron" align:"center">
           <br> <h5> Buscar Préstamos <h5>
           <%= form_tag librarians_loans_url ,method: :get do =%>
           <%= text_field_tag :keyword, nil, placeholder: "Por usuario, libros y estado" %>
           <%= content_tag :button,class:"btn btn-info", type: :submit do %>
           Buscar

           <% end %>

           <% end %>
     </div>
</div>

applibrary/app/views/librarians/loans.html.erb
<div class="container">
<br>
<h3>Préstamos</h3>



<br>
<%= link_to 'Home', librarians_index_path, class:"btn btn-info" %>
<%=link_to 'Crear Préstamo',librarians_loans_new_loan_path , class:"btn btn-info"  %>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Número de Socio</th>
      <th>Usuario</th>
      <th>Libro</th>
      <th>Inicio</th>
      <th>Fin</th>
      <th>Estado</th>

    </tr>
  </thead>


    <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.user.id %></td>
        <td><%= loan.user.name %>&nbsp;<%= loan.user.lastname %></td>
        <td><%= loan.book.title%></td>
        <td><%= loan.start_Date %></td>
        <td><%= loan.return_Date %></td>
        <td><%= loan.state %></td>
        <td><%= link_to "Editar",edit_librarians_loans_path(loan.id) , class:"btn btn-info"%></td>
        <td><%= link_to "Borrar ",delete_librarians_loans_path( loan.id),class:"btn btn-warning" ,method: :delete, data: { confirm: '¿Deseas eliminar libro?' } %></td>
      </tr>
    <% end %>
    <br>
    <% if @loans.size == 0 %>
    "NO EXISTE PRÉSTAMO"
    <% end %>


</table>
</div>

applibrary/app/views/librarians/new_book.html.erb
<div class="container">
<br>
<h3>Nuevo Libro</h3>
<br>
<%= link_to 'Home', librarians_index_path , class:"btn btn-info"%>
<%= link_to 'Ver Libros', librarians_books_path , class:"btn btn-info" %>
<br><br>
<%= form_for :book , url: librarians_books_path do |book| %>
<% if @book.errors.any? %>
 <div id="errorExplanation">
   <h2><%= pluralize(@book.errors.count, "error") %> El libro no se puede crear</h2>
   <ul>
   <% @book.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
 <% end %>
    <div class="form-group">
      <%= book.label :Título %>
      <%= book.text_field :title %>
    </div>
    <div class="form-group">
      <%= book.label :Autor %>
      <%= book.text_field :author %>
    </div>
    <div class="form-group">
      <%= book.label :Editorial %>
      <%= book.text_field :editorial %>
    </div>
    <div class="form-group">
      <%= book.label :Año %>
      <%= book.date_field :year %>
    </div>

    <div class="form-group">
      Disponible<%= book.radio_button :state, "available" %>  </div>

    <div class="form-group">
      <%= book.label :isbn %>
      <%= book.text_field :isbn %>
    </div>

    <div class="form-group">

      <%= book.submit 'Guardar', class:"btn btn-info" %>

    </div>


<% end %>
</div>

applibrary/app/views/librarians/new_loan.html.erb
<div class="container">
<br>
<h3>Crear préstamo</h3>
<br>
<%= link_to 'Home', librarians_index_path ,class:"btn btn-info" %>
<%= link_to 'Ver Préstamos', librarians_loans_path, class:"btn btn-info"  %><br><br>

<%= form_for :loan , url: librarians_loans_path do |loan| %>





      <div class="form-group">
        <%= loan.label :Código_Libro %>
        <%= loan.text_field :book_id %>
      </div>

      <div class="form-group">

      <%= loan.label :Número_Socio %>
      <%= loan.text_field :user_id %>
      </div>

    <div class="form-group">
      <%= loan.label :Inicio %>
      <%= loan.date_field :start_Date  %>
    </div>
    <div class="form-group">
      <%= loan.label :Fin  %>
      <%= loan.date_field :return_Date  %>
    </div>


    <div class="form-group">

    Activo<%= loan.radio_button :state, "actived" %>
    </div>

          <%= loan.submit 'Guardar', class:"btn btn-info " %>

    <% end %>
    <br> <br>

</div>

applibrary/app/views/librarians/new_user.html.erb
<div class="container">
<br>

<h3>Registrar Usuario</h3>
<br>
           

<%= link_to 'Home', librarians_index_path , class:"btn btn-info"  %>
<%= link_to 'Usuarios', librarians_users_path, class:"btn btn-info"  %>
<br><br><br>
<% if @user.errors.any? %>
 <div id="errorExplanation">
   <h2><%= pluralize(@user.errors.count, "error") %> El usuario no se puede editar</h2>
   <ul>
   <% @user.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
   <% end %>
   </ul>
 </div>
 <% end %>
<%= form_for :user , url: librarians_users_path do |user| %>

<div class="form-group">
<%= user.label :Nombre %>
<%= user.text_field :name %>
</div>
<div class="form-group">
<%= user.label :Apellido %>
<%= user.text_field :lastname %>
</div>
<div class="form-group">
<%= user.label :DNI %>
<%= user.number_field :dni %>
</div>
<div class="form-group">
<%= user.label :Email %>
<%= user.email_field :email %>
</div>

<div class="form-group">
<%= user.label :Teléfono %>
<%= user.text_field :phone %>
</div>
<div class="form-group">
<%= user.label :Contraseña %>
<%= user.text_field :password %>
</div>
<div class="form-group">
<%= user.label :Confirmación %>
<%= user.text_field :password_confirmation %>
</div>


    <div>

      <%= user.submit 'Guardar'  , class:"btn btn-info"   %>

    </div>


<% end %>

applibrary/app/views/librarians/show_book.html.erb
<div class="container">
<br>

<h3>Libro </h3>
<br>
<div class="form-group">
  <strong>Título:</strong>
  <%= @book.title %>
</div>
<div class="form-group">
  <strong>Autor:</strong>
  <%= @book.author %>
</div>
<div class="form-group">
  <strong>Editorial</strong>
  <%= @book.editorial %>
</div>
<div class="form-group">
  <strong> Año de publicación:</strong>
  <%= @book.year %>
</div>
<div class="form-group">
  <strong>ISBN</strong>
  <%= @book.isbn %>
</div>
<div class="form-group">
  <strong>Estado</strong>
  <%= @book.state %>
</p>

<%= link_to 'Home', librarians_books_path, class:"btn btn-info" %>

applibrary/app/views/librarians/show_user.html.erb
<h1>Libro </h1>

<p>
  <strong> Nombre:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Apellido</strong>
  <%= @user.lastname %>
</p>
<p>
  <strong> DNI:</strong>
  <%= @user.dni %>
</p>
<p>
  <strong>Email</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Teléfono</strong>
  <%= @user.phone %>
</p>
<p>
  <strong>Contraseña</strong>
  <%= @user.password %>
</p>
<p>
  <strong>Confirma Contraseña</strong>
  <%= @user.password_confirmation %>
</p>



<%= link_to 'Editar', :action => :edit_user, :id => @user.id %>
<%= link_to 'Volver', librarians_books_path %>

applibrary/app/views/librarians/users.html.erb
<div class="container">
<br>
<h3>Usuarios</h3>

<br>
<%= link_to 'Home', librarians_index_path, class:"btn btn-info" %>
<%=link_to 'Registrar usuario',librarians_users_signup_path , class:"btn btn-info" %>
<br><br>

<br>

 <%= form_tag librarians_users_url ,method: :get do =%>
   <%= text_field_tag :keyword, nil, placeholder: "Buscar por DNI " %>
   <%= content_tag :button,class:"btn btn-info",type: :submit do  %>
     Buscar

 <% end %>
 <% end %>

<br><br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Socio</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>DNI</th>
      <th>Email</th>
      <th>Telefono</th>

    </tr>
  </thead>


    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.dni %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>


        <td><%= link_to "Editar",edit_librarians_users_path(user.id),class:"btn btn-info" %></td>
        <td><%= link_to "Borrar",delete_librarians_users_path(user.id),class:"btn btn-warning" ,method: :delete, data: { confirm: '¿Deseas eliminar al usuario?', } %></td>
      </tr>

    <% end %>
    <% if @users.size == 0 %>
    "USUARIO NO ENCONTRADO"
    <% end %>



</table>
</div>